# SPDX-FileCopyrightText: 2026 Vabax and VabaxOS contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Orca 48's settings for the names of the settings pages (block 9, ADR-0027).

The pages name each setting as Orca 50 did in dconf, (group, key). Orca 48
(Debian 13) keeps them in JSON under its older names. Made from the
mapping that Orca 50.2 declares for its migration from JSON (migration_key
of every setting) and from the defaults of Orca 48.1 (orca/settings.py):
(group, key): (Orca 48 name, kind, Orca 48 default, {nick: number} or None).
kind: bool, int, float, str, strv, enum (the JSON value is the number of
the nick) or strenum (the JSON value is the nick itself).

Settings of Orca 50 that Orca 48 does not have are missing here: the pages
hide them.
"""

SETTINGS = {
    ('braille', 'braille-progress-bar-updates'): ('brailleProgressBarUpdates', 'bool', False, None),
    ('braille', 'contracted-braille'): ('enableContractedBraille', 'bool', False, None),
    ('braille', 'contraction-table'): ('brailleContractionTable', 'str', '', None),
    ('braille', 'display-ancestors'): ('enableBrailleContext', 'bool', None, None),
    ('braille', 'enabled'): ('enableBraille', 'bool', True, None),
    ('braille', 'flash-message-duration'): ('brailleFlashTime', 'int', 5000, None),
    ('braille', 'flash-messages'): ('enableFlashMessages', 'bool', True, None),
    ('braille', 'flash-messages-detailed'): ('flashIsDetailed', 'bool', True, None),
    ('braille', 'flash-messages-persistent'): ('flashIsPersistent', 'bool', False, None),
    ('braille', 'link-indicator'): ('brailleLinkIndicator', 'enum', 192, {'none': 0, 'dot7': 64, 'dot8': 128, 'dots78': 192}),
    ('braille', 'progress-bar-braille-interval'): ('progressBarBrailleInterval', 'int', None, None),
    ('braille', 'rolename-style'): ('brailleRolenameStyle', 'enum', 1, {'brief': 0, 'verbose': 1}),
    ('braille', 'selector-indicator'): ('brailleSelectorIndicator', 'enum', 192, {'none': 0, 'dot7': 64, 'dot8': 128, 'dots78': 192}),
    ('braille', 'text-attributes-indicator'): ('textAttributesBrailleIndicator', 'enum', 0, {'none': 0, 'dot7': 64, 'dot8': 128, 'dots78': 192}),
    ('braille', 'verbosity-level'): ('brailleVerbosityLevel', 'enum', 1, {'brief': 0, 'verbose': 1}),
    ('braille', 'word-wrap'): ('enableBrailleWordWrap', 'bool', False, None),
    ('caret-navigation', 'enabled'): ('caretNavigationEnabled', 'bool', True, None),
    ('caret-navigation', 'layout-mode'): ('layoutMode', 'bool', True, None),
    ('caret-navigation', 'triggers-focus-mode'): ('caretNavTriggersFocusMode', 'bool', False, None),
    ('chat', 'announce-buddy-typing'): ('chatAnnounceBuddyTyping', 'bool', False, None),
    ('chat', 'message-verbosity'): ('chatMessageVerbosity', 'enum', 0, {'all': 0, 'all-if-focused': 1, 'focused-channel': 2, 'active-channel': 3}),
    ('chat', 'room-histories'): ('chatRoomHistories', 'bool', False, None),
    ('chat', 'speak-room-name'): ('chatSpeakRoomName', 'bool', False, None),
    ('chat', 'speak-room-name-last'): ('presentChatRoomLast', 'bool', False, None),
    ('document', 'find-results-minimum-length'): ('findResultsMinimumLength', 'int', 4, None),
    ('document', 'find-results-verbosity'): ('findResultsVerbosity', 'enum', 2, {'none': 0, 'if-line-changed': 1, 'all': 2}),
    ('document', 'native-nav-triggers-focus-mode'): ('nativeNavTriggersFocusMode', 'bool', True, None),
    ('document', 'page-summary-on-load'): ('pageSummaryOnLoad', 'bool', True, None),
    ('document', 'say-all-on-load'): ('sayAllOnLoad', 'bool', True, None),
    ('flat-review', 'restricted'): ('flatReviewIsRestricted', 'bool', False, None),
    ('live-regions', 'present-from-inactive-tab'): ('presentLiveRegionFromInactiveTab', 'bool', False, None),
    ('mouse-review', 'enabled'): ('enableMouseReview', 'bool', False, None),
    ('mouse-review', 'present-tooltips'): ('presentToolTips', 'bool', False, None),
    ('say-all', 'announce-blockquote'): ('sayAllContextBlockquote', 'bool', True, None),
    ('say-all', 'announce-form'): ('sayAllContextNonLandmarkForm', 'bool', True, None),
    ('say-all', 'announce-grouping'): ('sayAllContextPanel', 'bool', True, None),
    ('say-all', 'announce-landmark'): ('sayAllContextLandmark', 'bool', True, None),
    ('say-all', 'announce-list'): ('sayAllContextList', 'bool', True, None),
    ('say-all', 'announce-table'): ('sayAllContextTable', 'bool', True, None),
    ('say-all', 'rewind-and-fast-forward'): ('rewindAndFastForwardInSayAll', 'bool', False, None),
    ('say-all', 'structural-navigation'): ('structNavInSayAll', 'bool', False, None),
    ('say-all', 'style'): ('sayAllStyle', 'enum', 1, {'line': 0, 'sentence': 1}),
    ('sound', 'beep-progress-bar-updates'): ('beepProgressBarUpdates', 'bool', False, None),
    ('sound', 'enabled'): ('enableSound', 'bool', True, None),
    ('sound', 'progress-bar-beep-interval'): ('progressBarBeepInterval', 'int', 0, None),
    ('sound', 'volume'): ('soundVolume', 'float', 0.5, None),
    ('speech', 'always-announce-selected-range-in-spreadsheet'): ('alwaysSpeakSelectedSpreadsheetRange', 'bool', False, None),
    ('speech', 'announce-blockquote'): ('speakContextBlockquote', 'bool', True, None),
    ('speech', 'announce-cell-coordinates'): ('speakCellCoordinates', 'bool', True, None),
    ('speech', 'announce-cell-headers'): ('speakCellHeaders', 'bool', True, None),
    ('speech', 'announce-cell-span'): ('speakCellSpan', 'bool', True, None),
    ('speech', 'announce-form'): ('speakContextNonLandmarkForm', 'bool', True, None),
    ('speech', 'announce-grouping'): ('speakContextPanel', 'bool', True, None),
    ('speech', 'announce-landmark'): ('speakContextLandmark', 'bool', True, None),
    ('speech', 'announce-list'): ('speakContextList', 'bool', True, None),
    ('speech', 'announce-spreadsheet-cell-coordinates'): ('speakSpreadsheetCoordinates', 'bool', True, None),
    ('speech', 'announce-table'): ('speakContextTable', 'bool', True, None),
    ('speech', 'capitalization-style'): ('capitalizationStyle', 'strenum', 'none', {'none': 0, 'spell': 1, 'icon': 2}),
    ('speech', 'enable'): ('enableSpeech', 'bool', True, None),
    ('speech', 'insert-pauses-between-utterances'): ('enablePauseBreaks', 'bool', True, None),
    ('speech', 'messages-are-detailed'): ('messagesAreDetailed', 'bool', True, None),
    ('speech', 'only-speak-displayed-text'): ('onlySpeakDisplayedText', 'bool', False, None),
    ('speech', 'progress-bar-speech-interval'): ('progressBarUpdateInterval', 'int', 10, None),
    ('speech', 'progress-bar-speech-verbosity'): ('progressBarVerbosity', 'enum', 1, {'all': 0, 'application': 1, 'window': 2}),
    ('speech', 'punctuation-level'): ('verbalizePunctuationStyle', 'enum', 1, {'all': 0, 'most': 1, 'some': 2, 'none': 3}),
    ('speech', 'repeated-character-limit'): ('repeatCharacterLimit', 'int', 4, None),
    ('speech', 'speak-blank-lines'): ('speakBlankLines', 'bool', True, None),
    ('speech', 'speak-description'): ('speakDescription', 'bool', True, None),
    ('speech', 'speak-indentation-and-justification'): ('enableSpeechIndentation', 'bool', False, None),
    ('speech', 'speak-misspelled-indicator'): ('speakMisspelledIndicator', 'bool', True, None),
    ('speech', 'speak-numbers-as-digits'): ('speakNumbersAsDigits', 'bool', False, None),
    ('speech', 'speak-position-in-set'): ('enablePositionSpeaking', 'bool', False, None),
    ('speech', 'speak-progress-bar-updates'): ('speakProgressBarUpdates', 'bool', True, None),
    ('speech', 'speak-row-in-document-table'): ('readFullRowInDocumentTable', 'bool', True, None),
    ('speech', 'speak-row-in-gui-table'): ('readFullRowInGUITable', 'bool', True, None),
    ('speech', 'speak-row-in-spreadsheet'): ('readFullRowInSpreadSheet', 'bool', False, None),
    ('speech', 'speak-tutorial-messages'): ('enableTutorialMessages', 'bool', True, None),
    ('speech', 'speak-widget-mnemonic'): ('enableMnemonicSpeaking', 'bool', False, None),
    ('speech', 'speech-server-factory'): ('speechServerFactory', 'str', 'speechdispatcherfactory', None),
    ('speech', 'use-color-names'): ('useColorNames', 'bool', True, None),
    ('speech', 'use-pronunciation-dictionary'): ('usePronunciationDictionary', 'bool', True, None),
    ('speech', 'verbosity-level'): ('speechVerbosityLevel', 'enum', 1, {'brief': 0, 'verbose': 1}),
    ('spellcheck', 'present-context'): ('spellcheckPresentContext', 'bool', True, None),
    ('spellcheck', 'spell-error'): ('spellcheckSpellError', 'bool', True, None),
    ('spellcheck', 'spell-suggestion'): ('spellcheckSpellSuggestion', 'bool', True, None),
    ('structural-navigation', 'enabled'): ('structuralNavigationEnabled', 'bool', True, None),
    ('structural-navigation', 'large-object-text-length'): ('largeObjectTextLength', 'int', 75, None),
    ('structural-navigation', 'triggers-focus-mode'): ('structNavTriggersFocusMode', 'bool', False, None),
    ('structural-navigation', 'wraps'): ('wrappedStructuralNavigation', 'bool', True, None),
    ('system-information', 'date-format'): ('presentDateFormat', 'str', '%x', None),
    ('system-information', 'time-format'): ('presentTimeFormat', 'str', '%X', None),
    ('table-navigation', 'skip-blank-cells'): ('skipBlankCells', 'bool', False, None),
    ('text-attributes', 'attributes-to-braille'): ('textAttributesToBraille', 'strv', [], None),
    ('text-attributes', 'attributes-to-speak'): ('textAttributesToSpeak', 'strv', [], None),
    ('typing-echo', 'action-keys'): ('enableActionKeys', 'bool', True, None),
    ('typing-echo', 'alphabetic-keys'): ('enableAlphabeticKeys', 'bool', True, None),
    ('typing-echo', 'character-echo'): ('enableEchoByCharacter', 'bool', False, None),
    ('typing-echo', 'diacritical-keys'): ('enableDiacriticalKeys', 'bool', False, None),
    ('typing-echo', 'function-keys'): ('enableFunctionKeys', 'bool', True, None),
    ('typing-echo', 'key-echo'): ('enableKeyEcho', 'bool', True, None),
    ('typing-echo', 'modifier-keys'): ('enableModifierKeys', 'bool', True, None),
    ('typing-echo', 'navigation-keys'): ('enableNavigationKeys', 'bool', False, None),
    ('typing-echo', 'numeric-keys'): ('enableNumericKeys', 'bool', True, None),
    ('typing-echo', 'punctuation-keys'): ('enablePunctuationKeys', 'bool', True, None),
    ('typing-echo', 'sentence-echo'): ('enableEchoBySentence', 'bool', False, None),
    ('typing-echo', 'space'): ('enableSpace', 'bool', True, None),
    ('typing-echo', 'word-echo'): ('enableEchoByWord', 'bool', False, None),
}

# Orca 50 settings without an Orca 48 counterpart, for the record.
MISSING = [
    ('braille', 'computer-braille-at-cursor', 'enableComputerBrailleAtCursor'),
    ('braille', 'end-of-line-indicator', 'enableBrailleEOL'),
    ('braille', 'monitor-background', 'brailleMonitorBackground'),
    ('braille', 'monitor-cell-count', 'brailleMonitorCellCount'),
    ('braille', 'monitor-foreground', 'brailleMonitorForeground'),
    ('braille', 'monitor-show-dots', 'brailleMonitorShowDots'),
    ('braille', 'present-mnemonics', 'displayObjectMnemonic'),
    ('braille', 'progress-bar-braille-verbosity', 'progressBarBrailleVerbosity'),
    ('document', 'auto-sticky-focus-mode', 'autoStickyFocusModeForWebApps'),
    ('live-regions', 'enabled', 'enableLiveRegions'),
    ('sound', 'progress-bar-beep-verbosity', 'progressBarBeepVerbosity'),
    ('speech', 'auto-language-switching', 'enableAutoLanguageSwitching'),
    ('speech', 'monitor-background', 'speechMonitorBackground'),
    ('speech', 'monitor-font-size', 'speechMonitorFontSize'),
    ('speech', 'monitor-foreground', 'speechMonitorForeground'),
    ('speech', 'speak-indentation-only-if-changed', 'speakIndentationOnlyIfChanged'),
    ('table-navigation', 'enabled', 'tableNavigationEnabled'),
]
