# SPDX-FileCopyrightText: 2026 Vabax and VabaxOS contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Orca 50.2's keyboard commands (block 10), read from Orca itself in the
VabaxOS live system (every module's set_up_commands, plus the default
script): (name, group, description, desktop key, laptop key). A key is
(keysym, modifiers, clicks); modifiers: 1 Shift, 4 Ctrl, 8 Alt, 256 the
screen reader key. Group and description are Orca's English strings:
Orca's own translations are used for them (gettext domain "orca").
"""

COMMANDS = [
    ('show_actions_list', 'Actions', 'Show actions list', ('a', 257, 1), ('a', 257, 1)),
    ('toggle_braille_monitor', 'Braille', 'Toggle the on-screen braille display on and off', None, None),
    ('end_of_file', 'Caret navigation', 'Go to the bottom of the file', ('End', 4, 1), ('End', 4, 1)),
    ('end_of_line', 'Caret navigation', 'Go to the end of the line', ('End', 0, 1), ('End', 0, 1)),
    ('next_character', 'Caret navigation', 'Go to next character', ('Right', 0, 1), ('Right', 0, 1)),
    ('next_line', 'Caret navigation', 'Go to next line', ('Down', 0, 1), ('Down', 0, 1)),
    ('next_word', 'Caret navigation', 'Go to next word', ('Right', 4, 1), ('Right', 4, 1)),
    ('previous_character', 'Caret navigation', 'Go to previous character', ('Left', 0, 1), ('Left', 0, 1)),
    ('previous_line', 'Caret navigation', 'Go to previous line', ('Up', 0, 1), ('Up', 0, 1)),
    ('previous_word', 'Caret navigation', 'Go to previous word', ('Left', 4, 1), ('Left', 4, 1)),
    ('start_of_file', 'Caret navigation', 'Go to the top of the file', ('Home', 4, 1), ('Home', 4, 1)),
    ('start_of_line', 'Caret navigation', 'Go to the beginning of the line', ('Home', 0, 1), ('Home', 0, 1)),
    ('toggle_enabled', 'Caret navigation', 'Switch between native and screen-reader caret navigation', ('F12', 256, 1), ('F12', 256, 1)),
    ('toggle_layout_mode', 'Caret navigation', 'Toggle layout mode', None, None),
    ('chat_next_message', 'Chat', 'Present next chat room message', None, None),
    ('chat_previous_message', 'Chat', 'Present previous chat room message', None, None),
    ('chat_toggle_buddy_typing', 'Chat', 'Toggle typing announcements', None, None),
    ('chat_toggle_message_histories', 'Chat', 'Toggle chat room specific message histories', None, None),
    ('chat_toggle_room_name_prefix', 'Chat', 'Toggle room name presentation', None, None),
    ('present_clipboard_contents', 'Clipboard', 'Present clipboard contents', None, None),
    ('clear_atspi_app_cache', 'Debugging Tools', 'Clear the AT-SPI cache for the current application', None, None),
    ('cycleDebugLevelHandler', 'Debugging Tools', 'Cycle the debug level at run time', None, None),
    ('appPreferencesSettingsHandler', 'Default', 'Display the application preferences configuration dialog', ('space', 260, 1), ('space', 260, 1)),
    ('bypass_mode_toggle', 'Default', 'Toggle all Orca command keys', ('BackSpace', 8, 1), ('BackSpace', 8, 1)),
    ('contractedBrailleHandler', 'Default', 'Turn contracted braille on and off', None, None),
    ('cycleKeyEchoHandler', 'Default', 'Cycle to the next key echo level', None, None),
    ('leftClickReviewItemHandler', 'Default', 'Perform left click on current item', ('KP_Divide', 0, 1), ('7', 256, 1)),
    ('panBrailleLeftHandler', 'Default', 'Pan the braille display to the left', None, None),
    ('panBrailleRightHandler', 'Default', 'Pan the braille display to the right', None, None),
    ('preferencesSettingsHandler', 'Default', 'Display the preferences configuration dialog', ('space', 256, 1), ('space', 256, 1)),
    ('rightClickReviewItemHandler', 'Default', 'Perform right click on current item', ('KP_Multiply', 0, 1), ('8', 256, 1)),
    ('routePointerToItemHandler', 'Default', 'Route the pointer to the current item', ('KP_Divide', 256, 1), ('9', 256, 1)),
    ('sayAllHandler', 'Default', 'Speak entire document', ('KP_Add', 0, 1), ('semicolon', 256, 1)),
    ('shutdownHandler', 'Default', 'Quit the screen reader', None, None),
    ('enable_sticky_browse_mode', 'Documents', 'Enable sticky browse mode', ('a', 256, 3), ('a', 256, 3)),
    ('enable_sticky_focus_mode', 'Documents', 'Enable sticky focus mode', ('a', 256, 2), ('a', 256, 2)),
    ('toggle_presentation_mode', 'Documents', 'Switch between browse mode and focus mode', ('a', 256, 1), ('a', 256, 1)),
    ('findHandler', 'Find', 'Open the Find dialog', ('KP_Delete', 0, 1), ('bracketleft', 256, 1)),
    ('findNextHandler', 'Find', 'Search for the next instance of a string', ('KP_Delete', 256, 1), ('bracketright', 256, 1)),
    ('findPreviousHandler', 'Find', 'Search for the previous instance of a string', ('KP_Delete', 257, 1), ('bracketright', 260, 1)),
    ('flatReviewAppendHandler', 'Flat review', 'Append the contents under flat review to the clipboard', None, None),
    ('flatReviewCopyHandler', 'Flat review', 'Copy the contents under flat review to the clipboard', None, None),
    ('flatReviewSayAllHandler', 'Flat review', 'Speak entire window using flat review', ('KP_Add', 0, 2), ('semicolon', 256, 2)),
    ('flatReviewToggleRestrictHandler', 'Flat review', 'Toggle restricting flat review to the current object', None, None),
    ('reviewAboveHandler', 'Flat review', 'Move flat review to the word above the current word', ('KP_Left', 256, 1), ('j', 260, 1)),
    ('reviewBelowHandler', 'Flat review', 'Move flat review to the word below the current word', ('KP_Right', 256, 1), ('l', 260, 1)),
    ('reviewBottomLeftHandler', 'Flat review', 'Move flat review to the bottom left', None, None),
    ('reviewCurrentAccessibleHandler', 'Flat review', 'Speak the current flat review object', ('KP_Begin', 256, 1), ('k', 260, 1)),
    ('reviewCurrentCharacterHandler', 'Flat review', 'Speak the current flat review character', ('KP_Down', 0, 1), ('comma', 256, 1)),
    ('reviewCurrentItemHandler', 'Flat review', 'Speak the current flat review item or word', ('KP_Begin', 0, 1), ('k', 256, 1)),
    ('reviewCurrentLineHandler', 'Flat review', 'Speak the current flat review line', ('KP_Up', 0, 1), ('i', 256, 1)),
    ('reviewEndHandler', 'Flat review', 'Move flat review to the end position', ('KP_Page_Up', 256, 1), ('o', 260, 1)),
    ('reviewEndOfLineHandler', 'Flat review', 'Move flat review to the end of the line', ('KP_End', 256, 1), ('m', 260, 1)),
    ('reviewHomeHandler', 'Flat review', 'Move flat review to the home position', ('KP_Home', 256, 1), ('u', 260, 1)),
    ('reviewNextCharacterHandler', 'Flat review', 'Move flat review to the next character', ('KP_Page_Down', 0, 1), ('period', 256, 1)),
    ('reviewNextItemHandler', 'Flat review', 'Move flat review to the next item or word', ('KP_Right', 0, 1), ('l', 256, 1)),
    ('reviewNextLineHandler', 'Flat review', 'Move flat review to the beginning of the next line', ('KP_Page_Up', 0, 1), ('o', 256, 1)),
    ('reviewPhoneticCurrentItemHandler', 'Flat review', 'Phonetically spell the current flat review item or word', ('KP_Begin', 0, 3), ('k', 256, 3)),
    ('reviewPhoneticCurrentLineHandler', 'Flat review', 'Phonetically spell the current flat review line', ('KP_Up', 0, 3), ('i', 256, 3)),
    ('reviewPreviousCharacterHandler', 'Flat review', 'Move flat review to the previous character', ('KP_End', 0, 1), ('m', 256, 1)),
    ('reviewPreviousItemHandler', 'Flat review', 'Move flat review to the previous item or word', ('KP_Left', 0, 1), ('j', 256, 1)),
    ('reviewPreviousLineHandler', 'Flat review', 'Move flat review to the beginning of the previous line', ('KP_Home', 0, 1), ('u', 256, 1)),
    ('reviewSpellCurrentCharacterHandler', 'Flat review', 'Phonetically speak the current flat review character', ('KP_Down', 0, 2), ('comma', 256, 2)),
    ('reviewSpellCurrentItemHandler', 'Flat review', 'Spell the current flat review item or word', ('KP_Begin', 0, 2), ('k', 256, 2)),
    ('reviewSpellCurrentLineHandler', 'Flat review', 'Spell the current flat review line', ('KP_Up', 0, 2), ('i', 256, 2)),
    ('reviewUnicodeCurrentCharacterHandler', 'Flat review', 'Speak unicode value of the current flat review character', ('KP_Down', 0, 3), ('comma', 256, 3)),
    ('showContentsHandler', 'Flat review', 'Show flat review contents', None, None),
    ('toggleFlatReviewModeHandler', 'Flat review', 'Enter and exit flat review mode', ('KP_Subtract', 0, 1), ('p', 256, 1)),
    ('enterLearnModeHandler', 'Learn mode', 'Enter learn mode.  Press escape to exit learn mode', ('h', 256, 1), ('h', 256, 1)),
    ('advance_live_politeness', 'Live regions', 'Advance live region politeness setting', None, None),
    ('present_next_live_region_message', 'Live regions', 'Present next live region message', None, None),
    ('present_previous_live_region_message', 'Live regions', 'Present previous live region message', None, None),
    ('toggle_live_region_presentation', 'Live regions', 'Set default live region politeness level to off', None, None),
    ('toggle_live_region_support', 'Live regions', 'Monitor live regions', ('backslash', 256, 1), ('backslash', 256, 1)),
    ('toggleMouseReviewHandler', 'Mouse review', 'Toggle mouse review mode', None, None),
    ('present_last_notification', 'Notification presenter', 'Present last notification message', None, None),
    ('present_next_notification', 'Notification presenter', 'Present next notification message', None, None),
    ('present_previous_notification', 'Notification presenter', 'Present previous notification message', None, None),
    ('show_notification_list', 'Notification presenter', 'Present notification messages list', None, None),
    ('getStatusBarHandler', 'Object details', 'Present the status bar', ('KP_Enter', 256, 2), ('slash', 256, 2)),
    ('getTitleHandler', 'Object details', 'Present the title bar', ('KP_Enter', 256, 1), ('slash', 256, 1)),
    ('presentSizeAndPositionHandler', 'Object details', 'Present size and location of current object', None, None),
    ('present_cell_formula', 'Object details', 'Present the formula for the current cell', ('equal', 256, 1), None),
    ('present_default_button', 'Object details', 'Present the default button', ('e', 256, 1), ('e', 256, 1)),
    ('readCharAttributesHandler', 'Object details', 'Read the attributes associated with the current text character', ('f', 256, 1), ('f', 256, 1)),
    ('whereAmIBasicHandler', 'Object details', 'Perform the basic Where Am I operation', ('KP_Enter', 0, 1), ('Return', 256, 1)),
    ('whereAmIDetailedHandler', 'Object details', 'Perform the detailed Where Am I operation', ('KP_Enter', 0, 2), ('Return', 256, 2)),
    ('whereAmILinkHandler', 'Object details', 'Speak link details', None, None),
    ('whereAmISelectionHandler', 'Object details', 'Speak the current selection', ('Up', 257, 1), ('Up', 257, 1)),
    ('object_navigator_down', 'Object navigation', 'Go to the first child of the object with navigator focus.', ('Down', 260, 1), ('Down', 260, 1)),
    ('object_navigator_next', 'Object navigation', 'Go to the next sibling of the object with navigator focus.', ('Right', 260, 1), ('Right', 260, 1)),
    ('object_navigator_perform_action', 'Object navigation', 'Click on the object with navigator focus.', ('Return', 260, 1), ('Return', 260, 1)),
    ('object_navigator_previous', 'Object navigation', 'Go to the previous sibling of the object with navigator focus.', ('Left', 260, 1), ('Left', 260, 1)),
    ('object_navigator_toggle_simplify', 'Object navigation', 'Toggle simplified object navigation.', ('s', 260, 1), ('s', 260, 1)),
    ('object_navigator_up', 'Object navigation', 'Go to the parent of the object with navigator focus.', ('Up', 260, 1), ('Up', 260, 1)),
    ('cycleSettingsProfileHandler', 'Profiles', 'Cycle to the next settings profile', None, None),
    ('presentCurrentProfileHandler', 'Profiles', 'Present the current profile', None, None),
    ('toggle_sleep_mode', 'Sleep mode', 'Toggle sleep mode for the current application', ('q', 13, 1), ('q', 13, 1)),
    ('changeNumberStyleHandler', 'Speech and verbosity', 'Change spoken number style', None, None),
    ('cycleCapitalizationStyleHandler', 'Speech and verbosity', 'Cycle to the next capitalization style', None, None),
    ('cycleSpeakingPunctuationLevelHandler', 'Speech and verbosity', 'Cycle to the next speaking of punctuation level', None, None),
    ('cycleSynthesizerHandler', 'Speech and verbosity', 'Cycle to the next speech synthesizer', None, None),
    ('decreaseSpeechPitchHandler', 'Speech and verbosity', 'Decrease the speech pitch', None, None),
    ('decreaseSpeechRateHandler', 'Speech and verbosity', 'Decrease the speech rate', None, None),
    ('decreaseSpeechVolumeHandler', 'Speech and verbosity', 'Decrease the speech volume', None, None),
    ('increaseSpeechPitchHandler', 'Speech and verbosity', 'Increase the speech pitch', None, None),
    ('increaseSpeechRateHandler', 'Speech and verbosity', 'Increase the speech rate', None, None),
    ('increaseSpeechVolumeHandler', 'Speech and verbosity', 'Increase the speech volume', None, None),
    ('toggleSilenceSpeechHandler', 'Speech and verbosity', 'Toggle the silencing of speech', ('s', 256, 1), ('s', 256, 1)),
    ('toggleSpeakingIndentationJustificationHandler', 'Speech and verbosity', 'Toggle the speaking of indentation and justification', None, None),
    ('toggleSpeechVerbosityHandler', 'Speech and verbosity', 'Toggle speech verbosity level', ('v', 256, 1), ('v', 256, 1)),
    ('toggleTableCellReadModeHandler', 'Speech and verbosity', 'Toggle whether to read just the current table cell or the whole row', ('F11', 256, 1), ('F11', 256, 1)),
    ('toggle_speech_monitor', 'Speech and verbosity', 'Toggle the on-screen speech display on and off', ('d', 257, 1), ('d', 257, 1)),
    ('container_end', 'Structural navigation', 'Go to end of container', ('comma', 0, 1), ('comma', 0, 1)),
    ('container_start', 'Structural navigation', 'Go to start of container', ('comma', 1, 1), ('comma', 1, 1)),
    ('last_live_region', 'Structural navigation', 'Go to the last live region which made an announcement', ('y', 0, 1), ('y', 0, 1)),
    ('list_blockquotes', 'Structural navigation', 'Display a list of blockquotes', ('q', 9, 1), ('q', 9, 1)),
    ('list_buttons', 'Structural navigation', 'Display a list of buttons', ('b', 9, 1), ('b', 9, 1)),
    ('list_checkboxes', 'Structural navigation', 'Display a list of check boxes', ('x', 9, 1), ('x', 9, 1)),
    ('list_clickables', 'Structural navigation', 'Display a list of clickables', ('a', 9, 1), ('a', 9, 1)),
    ('list_comboboxes', 'Structural navigation', 'Display a list of combo boxes', ('c', 9, 1), ('c', 9, 1)),
    ('list_entries', 'Structural navigation', 'Display a list of entries', ('e', 9, 1), ('e', 9, 1)),
    ('list_form_fields', 'Structural navigation', 'Display a list of form fields', ('f', 9, 1), ('f', 9, 1)),
    ('list_headings', 'Structural navigation', 'Display a list of headings', ('h', 9, 1), ('h', 9, 1)),
    ('list_headings_level_1', 'Structural navigation', 'Display a list of headings at level 1', ('1', 9, 1), ('1', 9, 1)),
    ('list_headings_level_2', 'Structural navigation', 'Display a list of headings at level 2', ('2', 9, 1), ('2', 9, 1)),
    ('list_headings_level_3', 'Structural navigation', 'Display a list of headings at level 3', ('3', 9, 1), ('3', 9, 1)),
    ('list_headings_level_4', 'Structural navigation', 'Display a list of headings at level 4', ('4', 9, 1), ('4', 9, 1)),
    ('list_headings_level_5', 'Structural navigation', 'Display a list of headings at level 5', ('5', 9, 1), ('5', 9, 1)),
    ('list_headings_level_6', 'Structural navigation', 'Display a list of headings at level 6', ('6', 9, 1), ('6', 9, 1)),
    ('list_iframes', 'Structural navigation', 'Display a list of internal frames', None, None),
    ('list_images', 'Structural navigation', 'Display a list of images', ('g', 9, 1), ('g', 9, 1)),
    ('list_landmarks', 'Structural navigation', 'Display a list of landmarks', ('m', 9, 1), ('m', 9, 1)),
    ('list_large_objects', 'Structural navigation', 'Display a list of large objects', ('o', 9, 1), ('o', 9, 1)),
    ('list_links', 'Structural navigation', 'Display a list of links', ('k', 9, 1), ('k', 9, 1)),
    ('list_list_items', 'Structural navigation', 'Display a list of list items', ('i', 9, 1), ('i', 9, 1)),
    ('list_lists', 'Structural navigation', 'Display a list of lists', ('l', 9, 1), ('l', 9, 1)),
    ('list_paragraphs', 'Structural navigation', 'Display a list of paragraphs', ('p', 9, 1), ('p', 9, 1)),
    ('list_radio_buttons', 'Structural navigation', 'Display a list of radio buttons', ('r', 9, 1), ('r', 9, 1)),
    ('list_tables', 'Structural navigation', 'Display a list of tables', ('t', 9, 1), ('t', 9, 1)),
    ('list_unvisited_links', 'Structural navigation', 'Display a list of unvisited links', ('u', 9, 1), ('u', 9, 1)),
    ('list_visited_links', 'Structural navigation', 'Display a list of visited links', ('v', 9, 1), ('v', 9, 1)),
    ('next_blockquote', 'Structural navigation', 'Go to next blockquote', ('q', 0, 1), ('q', 0, 1)),
    ('next_button', 'Structural navigation', 'Go to next button', ('b', 0, 1), ('b', 0, 1)),
    ('next_checkbox', 'Structural navigation', 'Go to next check box', ('x', 0, 1), ('x', 0, 1)),
    ('next_clickable', 'Structural navigation', 'Go to next clickable', ('a', 0, 1), ('a', 0, 1)),
    ('next_combobox', 'Structural navigation', 'Go to next combo box', ('c', 0, 1), ('c', 0, 1)),
    ('next_entry', 'Structural navigation', 'Go to next entry', ('e', 0, 1), ('e', 0, 1)),
    ('next_form_field', 'Structural navigation', 'Go to next form field', ('f', 0, 1), ('f', 0, 1)),
    ('next_heading', 'Structural navigation', 'Go to next heading', ('h', 0, 1), ('h', 0, 1)),
    ('next_heading_level_1', 'Structural navigation', 'Go to next heading at level 1', ('1', 0, 1), ('1', 0, 1)),
    ('next_heading_level_2', 'Structural navigation', 'Go to next heading at level 2', ('2', 0, 1), ('2', 0, 1)),
    ('next_heading_level_3', 'Structural navigation', 'Go to next heading at level 3', ('3', 0, 1), ('3', 0, 1)),
    ('next_heading_level_4', 'Structural navigation', 'Go to next heading at level 4', ('4', 0, 1), ('4', 0, 1)),
    ('next_heading_level_5', 'Structural navigation', 'Go to next heading at level 5', ('5', 0, 1), ('5', 0, 1)),
    ('next_heading_level_6', 'Structural navigation', 'Go to next heading at level 6', ('6', 0, 1), ('6', 0, 1)),
    ('next_iframe', 'Structural navigation', 'Go to next internal frame', None, None),
    ('next_image', 'Structural navigation', 'Go to next image', ('g', 0, 1), ('g', 0, 1)),
    ('next_landmark', 'Structural navigation', 'Go to next landmark', ('m', 0, 1), ('m', 0, 1)),
    ('next_large_object', 'Structural navigation', 'Go to next large object', ('o', 0, 1), ('o', 0, 1)),
    ('next_link', 'Structural navigation', 'Go to next link', ('k', 0, 1), ('k', 0, 1)),
    ('next_list', 'Structural navigation', 'Go to next list', ('l', 0, 1), ('l', 0, 1)),
    ('next_list_item', 'Structural navigation', 'Go to next list item', ('i', 0, 1), ('i', 0, 1)),
    ('next_live_region', 'Structural navigation', 'Go to next live region', ('d', 0, 1), ('d', 0, 1)),
    ('next_paragraph', 'Structural navigation', 'Go to next paragraph', ('p', 0, 1), ('p', 0, 1)),
    ('next_radio_button', 'Structural navigation', 'Go to next radio button', ('r', 0, 1), ('r', 0, 1)),
    ('next_separator', 'Structural navigation', 'Go to next separator', ('s', 0, 1), ('s', 0, 1)),
    ('next_table', 'Structural navigation', 'Go to next table', ('t', 0, 1), ('t', 0, 1)),
    ('next_unvisited_link', 'Structural navigation', 'Go to next unvisited link', ('u', 0, 1), ('u', 0, 1)),
    ('next_visited_link', 'Structural navigation', 'Go to next visited link', ('v', 0, 1), ('v', 0, 1)),
    ('previous_blockquote', 'Structural navigation', 'Go to previous blockquote', ('q', 1, 1), ('q', 1, 1)),
    ('previous_button', 'Structural navigation', 'Go to previous button', ('b', 1, 1), ('b', 1, 1)),
    ('previous_checkbox', 'Structural navigation', 'Go to previous check box', ('x', 1, 1), ('x', 1, 1)),
    ('previous_clickable', 'Structural navigation', 'Go to previous clickable', ('a', 1, 1), ('a', 1, 1)),
    ('previous_combobox', 'Structural navigation', 'Go to previous combo box', ('c', 1, 1), ('c', 1, 1)),
    ('previous_entry', 'Structural navigation', 'Go to previous entry', ('e', 1, 1), ('e', 1, 1)),
    ('previous_form_field', 'Structural navigation', 'Go to previous form field', ('f', 1, 1), ('f', 1, 1)),
    ('previous_heading', 'Structural navigation', 'Go to previous heading', ('h', 1, 1), ('h', 1, 1)),
    ('previous_heading_level_1', 'Structural navigation', 'Go to previous heading at level 1', ('1', 1, 1), ('1', 1, 1)),
    ('previous_heading_level_2', 'Structural navigation', 'Go to previous heading at level 2', ('2', 1, 1), ('2', 1, 1)),
    ('previous_heading_level_3', 'Structural navigation', 'Go to previous heading at level 3', ('3', 1, 1), ('3', 1, 1)),
    ('previous_heading_level_4', 'Structural navigation', 'Go to previous heading at level 4', ('4', 1, 1), ('4', 1, 1)),
    ('previous_heading_level_5', 'Structural navigation', 'Go to previous heading at level 5', ('5', 1, 1), ('5', 1, 1)),
    ('previous_heading_level_6', 'Structural navigation', 'Go to previous heading at level 6', ('6', 1, 1), ('6', 1, 1)),
    ('previous_iframe', 'Structural navigation', 'Go to previous internal frame', None, None),
    ('previous_image', 'Structural navigation', 'Go to previous image', ('g', 1, 1), ('g', 1, 1)),
    ('previous_landmark', 'Structural navigation', 'Go to previous landmark', ('m', 1, 1), ('m', 1, 1)),
    ('previous_large_object', 'Structural navigation', 'Go to previous large object', ('o', 1, 1), ('o', 1, 1)),
    ('previous_link', 'Structural navigation', 'Go to previous link', ('k', 1, 1), ('k', 1, 1)),
    ('previous_list', 'Structural navigation', 'Go to previous list', ('l', 1, 1), ('l', 1, 1)),
    ('previous_list_item', 'Structural navigation', 'Go to previous list item', ('i', 1, 1), ('i', 1, 1)),
    ('previous_live_region', 'Structural navigation', 'Go to previous live region', ('d', 1, 1), ('d', 1, 1)),
    ('previous_paragraph', 'Structural navigation', 'Go to previous paragraph', ('p', 1, 1), ('p', 1, 1)),
    ('previous_radio_button', 'Structural navigation', 'Go to previous radio button', ('r', 1, 1), ('r', 1, 1)),
    ('previous_separator', 'Structural navigation', 'Go to previous separator', ('s', 1, 1), ('s', 1, 1)),
    ('previous_table', 'Structural navigation', 'Go to previous table', ('t', 1, 1), ('t', 1, 1)),
    ('previous_unvisited_link', 'Structural navigation', 'Go to previous unvisited link', ('u', 1, 1), ('u', 1, 1)),
    ('previous_visited_link', 'Structural navigation', 'Go to previous visited link', ('v', 1, 1), ('v', 1, 1)),
    ('structural_navigator_mode_cycle', 'Structural navigation', 'Cycles to the next structural navigation mode', ('z', 256, 1), ('z', 256, 1)),
    ('presentDateHandler', 'System information', 'Present current date', ('t', 256, 2), ('t', 256, 2)),
    ('presentTimeHandler', 'System information', 'Present current time', ('t', 256, 1), ('t', 256, 1)),
    ('present_battery_status', 'System information', 'Present battery status', None, None),
    ('present_cpu_and_memory_usage', 'System information', 'Present CPU and memory usage', None, None),
    ('clear_dynamic_column_headers_row', 'Table navigation', 'Clear the dynamic column headers', ('r', 257, 2), ('r', 257, 2)),
    ('clear_dynamic_row_headers_column', 'Table navigation', 'Clear the dynamic row headers', ('c', 257, 2), ('c', 257, 2)),
    ('set_dynamic_column_headers_row', 'Table navigation', 'Set the row to use as dynamic column headers', ('r', 257, 1), ('r', 257, 1)),
    ('set_dynamic_row_headers_column', 'Table navigation', 'Set the column to use as dynamic row headers', ('c', 257, 1), ('c', 257, 1)),
    ('table_cell_beginning_of_row', 'Table navigation', 'Go to the beginning of the row', ('Left', 265, 1), ('Left', 265, 1)),
    ('table_cell_bottom_of_column', 'Table navigation', 'Go to the bottom of the column', ('Down', 265, 1), ('Down', 265, 1)),
    ('table_cell_down', 'Table navigation', 'Go down one cell', ('Down', 9, 1), ('Down', 9, 1)),
    ('table_cell_end_of_row', 'Table navigation', 'Go to the end of the row', ('Right', 265, 1), ('Right', 265, 1)),
    ('table_cell_first', 'Table navigation', 'Go to the first cell in a table', ('Home', 9, 1), ('Home', 9, 1)),
    ('table_cell_last', 'Table navigation', 'Go to the last cell in a table', ('End', 9, 1), ('End', 9, 1)),
    ('table_cell_left', 'Table navigation', 'Go left one cell', ('Left', 9, 1), ('Left', 9, 1)),
    ('table_cell_right', 'Table navigation', 'Go right one cell', ('Right', 9, 1), ('Right', 9, 1)),
    ('table_cell_top_of_column', 'Table navigation', 'Go to the top of the column', ('Up', 265, 1), ('Up', 265, 1)),
    ('table_cell_up', 'Table navigation', 'Go up one cell', ('Up', 9, 1), ('Up', 9, 1)),
    ('table_navigator_toggle_enabled', 'Table navigation', 'Toggle table navigation keys', ('t', 257, 1), ('t', 257, 1)),
]
